// wordList.js - Updated with proper accents

const wordList = [
    { pt: "Casa", en: "House" },
    { pt: "Amigo", en: "Friend" },
    { pt: "Escola", en: "School" },
    { pt: "Brinquedo", en: "Toy" },
    { pt: "Família", en: "Family" },
    { pt: "Felicidade", en: "Happiness" },
    { pt: "Cachorro", en: "Dog" },
    { pt: "Gato", en: "Cat" },
    { pt: "Praia", en: "Beach" },
    { pt: "Janela", en: "Window" },
    { pt: "Livro", en: "Book" },
    { pt: "Amarelo", en: "Yellow" },
    { pt: "Escrever", en: "To write" },
    { pt: "Leitura", en: "Reading" },
    { pt: "Coração", en: "Heart" },
    { pt: "Alegria", en: "Joy" },
    { pt: "Mesa", en: "Table" },
    { pt: "Cadeira", en: "Chair" },
    { pt: "Caneta", en: "Pen" },
    { pt: "Luz", en: "Light" },
    { pt: "Sol", en: "Sun" },
    { pt: "Lua", en: "Moon" },
    { pt: "Estrela", en: "Star" },
    { pt: "Céu", en: "Sky" },
    { pt: "Mar", en: "Sea" },
    { pt: "Rio", en: "River" },
    { pt: "Flor", en: "Flower" },
    { pt: "Árvore", en: "Tree" },
    { pt: "Fruta", en: "Fruit" },
    { pt: "Maçã", en: "Apple" },
    { pt: "Música", en: "Music" },
    { pt: "Dança", en: "Dance" },
    { pt: "Jogo", en: "Game" },
    { pt: "Bola", en: "Ball" },
    { pt: "Bicicleta", en: "Bicycle" },
    { pt: "Parque", en: "Park" },
    { pt: "Jardim", en: "Garden" },
    { pt: "Água", en: "Water" },
    { pt: "Pão", en: "Bread" },
    { pt: "Queijo", en: "Cheese" },
    { pt: "Abraço", en: "Hug" },
    { pt: "Beijo", en: "Kiss" },
    { pt: "Sonho", en: "Dream" },
    { pt: "Viagem", en: "Trip" },
    { pt: "Cidade", en: "City" },
    { pt: "País", en: "Country" },
    { pt: "Montanha", en: "Mountain" },
    { pt: "Neve", en: "Snow" },
    { pt: "Chuva", en: "Rain" },
    { pt: "Vento", en: "Wind" },
    { pt: "Fogo", en: "Fire" },
    { pt: "Terra", en: "Earth" },
    { pt: "Azul", en: "Blue" },
    { pt: "Verde", en: "Green" },
    { pt: "Vermelho", en: "Red" },
    { pt: "Branco", en: "White" },
    { pt: "Preto", en: "Black" },
    { pt: "Roxo", en: "Purple" },
    { pt: "Laranja", en: "Orange" },
    { pt: "Professor", en: "Teacher" },
    { pt: "Médico", en: "Doctor" },
    { pt: "Pai", en: "Father" },
    { pt: "Mãe", en: "Mother" },
    { pt: "Irmão", en: "Brother" },
    { pt: "Irmã", en: "Sister" },
    { pt: "Avó", en: "Grandmother" },
    { pt: "Avô", en: "Grandfather" },
    { pt: "Cabeça", en: "Head" },
    { pt: "Mão", en: "Hand" },
    { pt: "Pé", en: "Foot" },
    { pt: "Olho", en: "Eye" },
    { pt: "Orelha", en: "Ear" },
    { pt: "Número", en: "Number" },
    { pt: "História", en: "Story" },
    { pt: "Semana", en: "Week" },
    { pt: "Mês", en: "Month" },
    { pt: "Ano", en: "Year" },
    { pt: "Amanhã", en: "Tomorrow" },
    { pt: "Rápido", en: "Fast" },
    { pt: "Fácil", en: "Easy" },
    { pt: "Difícil", en: "Hard" },
    { pt: "Último", en: "Last" },
    { pt: "Próximo", en: "Next" },
    { pt: "Avião", en: "Airplane" },
    { pt: "Estação", en: "Station" },
    { pt: "Fotografia", en: "Photography" },
    { pt: "Mágico", en: "Magical" },
    { pt: "Príncipe", en: "Prince" },
    { pt: "Princesa", en: "Princess" },
    { pt: "Dragão", en: "Dragon" },
    { pt: "Solução", en: "Solution" },
    { pt: "Opinião", en: "Opinion" },
    { pt: "Diálogo", en: "Dialogue" },
    { pt: "Silêncio", en: "Silence" },
    { pt: "Lágrima", en: "Tear" },
    { pt: "Lição", en: "Lesson" },
    { pt: "Geração", en: "Generation" },
    { pt: "Nação", en: "Nation" },
    { pt: "Informação", en: "Information" },
    { pt: "Comunicação", en: "Communication" },
    { pt: "Atenção", en: "Attention" },
    { pt: "Canção", en: "Song" },
    { pt: "Leão", en: "Lion" },
    { pt: "Caminhão", en: "Truck" },
    { pt: "Balão", en: "Balloon" },
    { pt: "Sabão", en: "Soap" },
    { pt: "Calção", en: "Shorts" },
    { pt: "Portão", en: "Gate" },
    { pt: "Mamão", en: "Papaya" },
    { pt: "Limão", en: "Lemon" },
    { pt: "Botão", en: "Button" },
    { pt: "Pimentão", en: "Bell pepper" },
    { pt: "Violão", en: "Guitar" },
    { pt: "Coração", en: "Heart" },
    { pt: "Alemão", en: "German" },
    { pt: "Capitão", en: "Captain" },
    { pt: "Feijão", en: "Bean" },
    { pt: "Manhã", en: "Morning" },
    { pt: "Maçã", en: "Apple" },
    { pt: "Lã", en: "Wool" },
    { pt: "Anã", en: "Dwarf (female)" },
    { pt: "Romã", en: "Pomegranate" },
    { pt: "Hortelã", en: "Mint" },
    { pt: "Anfitriã", en: "Hostess" },
    { pt: "Órfã", en: "Orphan (female)" },
    { pt: "Bênção", en: "Blessing" },
    { pt: "Órgão", en: "Organ" },
    { pt: "Órfão", en: "Orphan (male)" },
    { pt: "Sótão", en: "Attic" },
    { pt: "Acórdão", en: "Ruling" },
    { pt: "Bênção", en: "Blessing" },
    { pt: "Pônei", en: "Pony" },
    { pt: "Tênis", en: "Sneakers" },
    { pt: "Lápis", en: "Pencil" },
    { pt: "Vírus", en: "Virus" },
    { pt: "Bônus", en: "Bonus" },
    { pt: "Ônibus", en: "Bus" },
    { pt: "Oásis", en: "Oasis" },
    { pt: "Grátis", en: "Free" },
    { pt: "Júri", en: "Jury" },
    { pt: "Táxi", en: "Taxi" },
    { pt: "Biquíni", en: "Bikini" },
    { pt: "Safári", en: "Safari" },
    { pt: "Esqui", en: "Ski" },
    { pt: "Ímã", en: "Magnet" },
    { pt: "Freguês", en: "Customer" },
    { pt: "Português", en: "Portuguese" },
    { pt: "Inglês", en: "English" },
    { pt: "Francês", en: "French" },
    { pt: "Japonês", en: "Japanese" },
    { pt: "Chinês", en: "Chinese" },
    { pt: "Mês", en: "Month" },
    { pt: "Três", en: "Three" },
    { pt: "Vez", en: "Time (turn)" },
    { pt: "Rapidez", en: "Speed" },
    { pt: "Xadrez", en: "Chess" },
    { pt: "Talvez", en: "Maybe" },
    { pt: "Cortês", en: "Courteous" },
    { pt: "Bebê", en: "Baby" },
    { pt: "Café", en: "Coffee" },
    { pt: "Chulé", en: "Stinky feet" },
    { pt: "Picolé", en: "Popsicle" },
    { pt: "Jacaré", en: "Alligator" },
    { pt: "Canapé", en: "Canape" },
    { pt: "Rapé", en: "Snuff" },
    { pt: "Maré", en: "Tide" },
    { pt: "Você", en: "You" },
    { pt: "Vovô", en: "Grandpa" },
    { pt: "Vovó", en: "Grandma" },
    { pt: "Robô", en: "Robot" },
    { pt: "Metrô", en: "Subway" },
    { pt: "Paletó", en: "Jacket" },
    { pt: "Jiló", en: "Jilo" },
    { pt: "Dominó", en: "Domino" },
    { pt: "Cipó", en: "Vine" },
    { pt: "Pó", en: "Powder" },
    { pt: "Dó", en: "Pity" },
    { pt: "Nó", en: "Knot" },
    { pt: "Siri", en: "Crab" },
    { pt: "Aqui", en: "Here" },
    { pt: "Ali", en: "There" },
    { pt: "Abacaxi", en: "Pineapple" },
    { pt: "Bambu", en: "Bamboo" },
    { pt: "Caju", en: "Cashew" },
    { pt: "Urubu", en: "Vulture" },
    { pt: "Tatu", en: "Armadillo" },
    { pt: "Menu", en: "Menu" },
    { pt: "Peru", en: "Turkey" },
    { pt: "Anzol", en: "Fishhook" },
    { pt: "Farol", en: "Lighthouse" },
    { pt: "Lençol", en: "Bedsheet" },
    { pt: "Girassol", en: "Sunflower" },
    { pt: "Espanhol", en: "Spanish" },
    { pt: "Futebol", en: "Soccer" },
    { pt: "Anel", en: "Ring" },
    { pt: "Papel", en: "Paper" },
    { pt: "Pincel", en: "Brush" },
    { pt: "Mel", en: "Honey" },
    { pt: "Cruel", en: "Cruel" },
    { pt: "Fiel", en: "Faithful" },
    { pt: "Aluguel", en: "Rent" },
    { pt: "Hotel", en: "Hotel" },
    { pt: "Pastel", en: "Pastry" },
    { pt: "Funil", en: "Funnel" },
    { pt: "Barril", en: "Barrel" },
    { pt: "Canil", en: "Kennel" },
    { pt: "Fuzil", en: "Rifle" },
    { pt: "Sutil", en: "Subtle" },
    { pt: "Gentil", en: "Kind" },
    { pt: "Azul", en: "Blue" },
    { pt: "Baú", en: "Chest" },
    { pt: "Jaú", en: "Jau (fish)" },
    { pt: "Saúde", en: "Health" },
    { pt: "Graúdo", en: "Large" },
    { pt: "Miúdo", en: "Tiny" },
    { pt: "Conteúdo", en: "Content" },
    { pt: "País", en: "Country" },
    { pt: "Raíz", en: "Root" },
    { pt: "Juíz", en: "Judge" },
    { pt: "Saí", en: "I left" },
    { pt: "Caí", en: "I fell" },
    { pt: "Atraí", en: "I attracted" },
    { pt: "Distraí", en: "I distracted" },
    { pt: "Herói", en: "Hero" },
    { pt: "Dói", en: "It hurts" },
    { pt: "Corrói", en: "It corrodes" },
    { pt: "Chapéu", en: "Hat" },
    { pt: "Troféu", en: "Trophy" },
    { pt: "Réu", en: "Defendant" },
    { pt: "Céu", en: "Sky" },
    { pt: "Véu", en: "Veil" },
    { pt: "Ilhéu", en: "Islet" },
    { pt: "Ações", en: "Actions" },
    { pt: "Balões", en: "Balloons" },
    { pt: "Canções", en: "Songs" },
    { pt: "Leões", en: "Lions" },
    { pt: "Opções", en: "Options" },
    { pt: "Paixões", en: "Passions" },
    { pt: "Mães", en: "Mothers" },
    { pt: "Pães", en: "Breads" },
    { pt: "Cães", en: "Dogs" },
    { pt: "Capitães", en: "Captains" },
    { pt: "Alemães", en: "Germans" },
    { pt: "Guardiães", en: "Guardians" },
    { pt: "Tabeliães", en: "Notaries" },
    { pt: "Mãos", en: "Hands" },
    { pt: "Grãos", en: "Grains" },
    { pt: "Órfãos", en: "Orphans" },
    { pt: "Sótãos", en: "Attics" },
    { pt: "Bênçãos", en: "Blessings" },
    { pt: "Órgãos", en: "Organs" },
    { pt: "Acórdãos", en: "Rulings" },
    { pt: "Cidadão", en: "Citizen" },
    { pt: "Cidadãos", en: "Citizens" },
    { pt: "Cristão", en: "Christian" },
    { pt: "Cristãos", en: "Christians" },
    { pt: "Anão", en: "Dwarf" },
    { pt: "Anões", en: "Dwarfs" },
    { pt: "O sol brilha", en: "The sun shines" },
    { pt: "Eu gosto de ler", en: "I like to read" },
    { pt: "O gato dorme", en: "The cat sleeps" },
    { pt: "A bola é redonda", en: "The ball is round" },
    { pt: "Onde você mora?", en: "Where do you live?" },
    { pt: "Qual é o seu nome?", en: "What is your name?" },
    { pt: "Eu gosto de pizza", en: "I like pizza" },
    { pt: "Que dia lindo", en: "What a beautiful day" },
    { pt: "O cachorro é marrom", en: "The dog is brown" },
    { pt: "A gata branca dorme", en: "The white cat sleeps" },
    { pt: "Vamos jogar lá fora", en: "Let's play outside" },
    { pt: "Minha cor favorita é azul", en: "My favorite color is blue" },
    { pt: "Eu tenho dez anos", en: "I am ten years old" },
    { pt: "A escola é divertida", en: "School is fun" },
    { pt: "Meu livro é novo", en: "My book is new" },
    { pt: "O sol está quente", en: "The sun is hot" },
    { pt: "A lua está cheia", en: "The moon is full" },
    { pt: "As estrelas brilham muito", en: "The stars shine brightly" },
    { pt: "Eu amo minha família", en: "I love my family" },
    { pt: "Nós somos bons amigos", en: "We are good friends" },
    { pt: "Ela canta muito bem", en: "She sings very well" },
    { pt: "Ele corre muito rápido", en: "He runs very fast" },
    { pt: "A árvore tem frutos", en: "The tree has fruits" },
    { pt: "Eu quero um sorvete", en: "I want an ice cream" },
    { pt: "O bolo de chocolate", en: "The chocolate cake" },
    { pt: "Feliz aniversário para você", en: "Happy birthday to you" },
    { pt: "Obrigado pela sua ajuda", en: "Thank you for your help" },
    { pt: "Com licença por favor", en: "Excuse me please" },
    { pt: "Desculpe pelo atraso", en: "Sorry for the delay" },
    { pt: "Eu não entendi", en: "I don't understand" },
    { pt: "Você pode repetir?", en: "Can you repeat?" },
    { pt: "Como você está hoje?", en: "How are you today?" },
    { pt: "Estou bem obrigado", en: "I am fine thank you" },
    { pt: "Até logo amigo", en: "See you later friend" },
    { pt: "Boa noite a todos", en: "Good night everyone" },
    { pt: "Bom dia para todos", en: "Good morning to all" },
    { pt: "Tenha um ótimo dia", en: "Have a great day" },
    { pt: "A água está fria", en: "The water is cold" },
    { pt: "O céu está nublado", en: "The sky is cloudy" },
    { pt: "Vai chover em breve", en: "It will rain soon" },
    { pt: "Eu gosto de desenhar", en: "I like to draw" },
    { pt: "Ela gosta de dançar", en: "She likes to dance" },
    { pt: "Ele joga futebol", en: "He plays soccer" },
    { pt: "Nós vamos ao cinema", en: "We are going to the movies" },
    { pt: "Eu visito meus avós", en: "I visit my grandparents" },
    { pt: "O pássaro voa alto", en: "The bird flies high" },
    { pt: "O peixe nada no rio", en: "The fish swims in the river" },
    { pt: "A borboleta é colorida", en: "The butterfly is colorful" },
    { pt: "O leão é o rei", en: "The lion is the king" },
    { pt: "O macaco come banana", en: "The monkey eats banana" },
    { pt: "A girafa é alta", en: "The giraffe is tall" },
    { pt: "O elefante é pesado", en: "The elephant is heavy" },
    { pt: "A tartaruga é lenta", en: "The turtle is slow" },
    { pt: "O coelho é rápido", en: "The rabbit is fast" },
    { pt: "A cobra rasteja", en: "The snake crawls" },
    { pt: "A aranha tece teia", en: "The spider weaves a web" },
    { pt: "A formiga trabalha duro", en: "The ant works hard" },
    { pt: "Eu uso o computador", en: "I use the computer" },
    { pt: "Ela fala ao telefone", en: "She talks on the phone" },
    { pt: "Ele assiste televisão", en: "He watches television" },
    { pt: "Nós ouvimos música", en: "We listen to music" },
    { pt: "A casa tem porta", en: "The house has a door" },
    { pt: "A chave abre a porta", en: "The key opens the door" },
    { pt: "O carro está na garagem", en: "The car is in the garage" },
    { pt: "A bicicleta é vermelha", en: "The bicycle is red" },
    { pt: "O trem faz barulho", en: "The train makes noise" },
    { pt: "O avião voa no céu", en: "The airplane flies in the sky" },
    { pt: "O barco navega no mar", en: "The boat sails on the sea" },
    { pt: "Eu escrevo uma carta", en: "I write a letter" },
    { pt: "Ela lê uma revista", en: "She reads a magazine" },
    { pt: "Ele olha o mapa", en: "He looks at the map" },
    { pt: "Nós viajamos nas férias", en: "We travel on vacation" },
    { pt: "Paris é a capital", en: "Paris is the capital" },
    { pt: "O Brasil é grande", en: "Brazil is big" },
    { pt: "Eu moro no Brasil", en: "I live in Brazil" },
    { pt: "A bandeira é bonita", en: "The flag is beautiful" },
    { pt: "Eu gosto da minha cidade", en: "I like my city" },
    { pt: "A praça tem flores", en: "The square has flowers" },
    { pt: "O parque tem árvores", en: "The park has trees" },
    { pt: "Eu brinco com amigos", en: "I play with friends" },
    { pt: "Minha mãe cozinha bem", en: "My mother cooks well" },
    { pt: "Meu pai trabalha muito", en: "My father works a lot" },
    { pt: "Eu ajudo em casa", en: "I help at home" },
    { pt: "Meu quarto é arrumado", en: "My room is tidy" },
    { pt: "A sala tem um sofá", en: "The living room has a sofa" },
    { pt: "Eu durmo na minha cama", en: "I sleep in my bed" },
    { pt: "A cozinha tem fogão", en: "The kitchen has a stove" },
    { pt: "O banheiro tem chuveiro", en: "The bathroom has a shower" },
    { pt: "Eu tomo café da manhã", en: "I eat breakfast" },
    { pt: "Nós almoçamos juntos", en: "We have lunch together" },
    { pt: "O jantar está pronto", en: "The dinner is ready" },
    { pt: "A sobremesa é doce", en: "The dessert is sweet" },
    { pt: "Eu bebo muita água", en: "I drink a lot of water" },
    { pt: "Suco de laranja é bom", en: "Orange juice is good" },
    { pt: "Leite com chocolate", en: "Milk with chocolate" },
    { pt: "Pão com manteiga", en: "Bread with butter" },
    { pt: "Queijo é amarelo", en: "Cheese is yellow" }
];
