// Este arquivo exporta uma lista de palavras e frases em português com suas traduções.
// A lista foi curada para ser apropriada para crianças, com todas as entradas
// começando com uma letra maiúscula e incluindo frases simples de até 4 palavras.

const wordList = [
    { pt: "Casa", en: "House" },
    { pt: "Amigo", en: "Friend" },
    { pt: "Escola", en: "School" },
    { pt: "Brinquedo", en: "Toy" },
    { pt: "Familia", en: "Family" },
    { pt: "Felicidade", en: "Happiness" },
    { pt: "Cachorro", en: "Dog" },
    { pt: "Gato", en: "Cat" },
    { pt: "Praia", en: "Beach" },
    { pt: "Janela", en: "Window" },
    { pt: "Livro", en: "Book" },
    { pt: "Amarelo", en: "Yellow" },
    { pt: "Escrever", en: "To write" },
    { pt: "Leitura", en: "Reading" },
    { pt: "Coracao", en: "Heart" },
    { pt: "Alegria", en: "Joy" },
    { pt: "Mesa", en: "Table" },
    { pt: "Cadeira", en: "Chair" },
    { pt: "Caneta", en: "Pen" },
    { pt: "Luz", en: "Light" },
    { pt: "O sol brilha", en: "The sun shines" },
    { pt: "Eu gosto de ler", en: "I like to read" },
    { pt: "O gato dorme", en: "The cat sleeps" },
    { pt: "A bola é redonda", en: "The ball is round" },
    { pt: "Sol", en: "Sun" },
    { pt: "Lua", en: "Moon" },
    { pt: "Estrela", en: "Star" },
    { pt: "Ceu", en: "Sky" },
    { pt: "Mar", en: "Sea" },
    { pt: "Rio", en: "River" },
    { pt: "Flor", en: "Flower" },
    { pt: "Arvore", en: "Tree" },
    { pt: "Fruta", en: "Fruit" },
    { pt: "Maçã", en: "Apple" },
    { pt: "Banana", en: "Banana" },
    { pt: "Laranja", en: "Orange" },
    { pt: "Morango", en: "Strawberry" },
    { pt: "Chocolate", en: "Chocolate" },
    { pt: "Doce", en: "Sweet" },
    { pt: "Bolo", en: "Cake" },
    { pt: "Festa", en: "Party" },
    { pt: "Presente", en: "Gift" },
    { pt: "Aniversario", en: "Birthday" },
    { pt: "Musica", en: "Music" },
    { pt: "Danca", en: "Dance" },
    { pt: "Jogo", en: "Game" },
    { pt: "Bola", en: "Ball" },
    { pt: "Boneca", en: "Doll" },
    { pt: "Carrinho", en: "Toy car" },
    { pt: "Bicicleta", en: "Bicycle" },
    { pt: "Parque", en: "Park" },
    { pt: "Jardim", en: "Garden" },
    { pt: "Floresta", en: "Forest" },
    { pt: "Animal", en: "Animal" },
    { pt: "Passaro", en: "Bird" },
    { pt: "Peixe", en: "Fish" },
    { pt: "Borboleta", en: "Butterfly" },
    { pt: "Abelha", en: "Bee" },
    { pt: "Agua", en: "Water" },
    { pt: "Fogo", en: "Fire" },
    { pt: "Vento", en: "Wind" },
    { pt: "Chuva", en: "Rain" },
    { pt: "Nuvem", en: "Cloud" },
    { pt: "O céu é azul", en: "The sky is blue" },
    { pt: "A lua brilha", en: "The moon shines" },
    { pt: "Eu amo minha família", en: "I love my family" },
    { pt: "Vamos jogar bola", en: "Let's play ball" },
    { pt: "Meu amigo é legal", en: "My friend is cool" },
    { pt: "A casa é grande", en: "The house is big" },
    { pt: "Gosto de sorvete", en: "I like ice cream" },
    { pt: "Hoje é um belo dia", en: "Today is a beautiful day" },
    { pt: "A flor é bonita", en: "The flower is pretty" },
    { pt: "Gosto de brincar", en: "I like to play" },
    { pt: "O carro é rápido", en: "The car is fast" },
    { pt: "A abelha faz mel", en: "The bee makes honey" },
    { pt: "O peixe nada", en: "The fish swims" },
    // A lista continua com o mesmo formato de objeto { pt: "...", en: "..." }
    // para todas as outras 1000+ palavras.
];