export const wordList = [
    "abacaxi", "abraço", "abril", "acampamento", "açúcar", "adeus", "adivinhar", "agora", "água", "agulha", 
    "alegria", "alface", "algodão", "almoço", "amarelo", "amigo", "amizade", "amor", "anel", "animal", 
    "aniversário", "anoitecer", "aprender", "aranha", "árvore", "asa", "assistir", "astro", "astronauta", 
    "atleta", "aventura", "avião", "avó", "avô", "azul", "azeite", "bailarina", "baixo", "bala", "baleia", 
    "banana", "bandeira", "barata", "barba", "barco", "barriga", "barulho", "batata", "beber", "beijo", 
    "beleza", "bicicleta", "bigode", "biscoito", "bola", "bolacha", "bolha", "bolo", "boneca", "bonito", 
    "borboleta", "botão", "braço", "brincar", "brinquedo", "bruxa", "cabelo", "cabeça", "cabra", "cachecol", 
    "cachorro", "caderno", "café", "caixa", "calça", "calor", "cama", "caminhão", "caminhar", "camisa", 
    "canção", "caneta", "cantar", "capitão", "caracol", "caranguejo", "carinho", "carne", "carro", "carta", 
    "carteira", "casa", "casaco", "castelo", "cavalo", "cebola", "cedo", "celular", "cemitério", "centro", 
    "céu", "chá", "chapéu", "chave", "cheiro", "chocolate", "chorar", "chover", "chuva", "cidade", 
    "ciência", "cinema", "cinto", "circo", "cobertor", "cobra", "coelho", "cofre", "coisa", "colar", 
    "colher", "colorido", "comer", "começar", "computador", "concha", "conversa", "coração", "coruja", 
    "cozinha", "criança", "crocodilo", "dançar", "dedo", "deixar", "dente", "dentro", "depois", "desenho", 
    "deserto", "diamante", "dicionário", "dinheiro", "dinossauro", "diretor", "doce", "doente", "domingo", 
    "dormir", "dragão", "elefante", "elevador", "encontrar", "endereço", "energia", "engraçado", "entrada", 
    "escada", "escola", "escorpião", "escrever", "escuro", "espaço", "espada", "espanha", "espelho", 
    "espirro", "esponja", "esporte", "esposa", "esqueleto", "esquecer", "esquerda", "esquina", "estação", 
    "estátua", "estrela", "estudar", "europa", "exame", "exemplo", "exercício", "exército", "explicar", 
    "fábrica", "faca", "fada", "falar", "família", "fantasma", "farinha", "farmácia", "fazenda", "fechar", 
    "feijão", "feliz", "feriado", "festa", "fevereiro", "filha", "filho", "filme", "final", "fio", "flor", 
    "floresta", "foca", "fofoca", "fogo", "foguete", "folha", "fome", "fonte", "formiga", "forno", "forte", 
    "fotografia", "frança", "frango", "frase", "freio", "frente", "frio", "fronteira", "fruta", "fumaça", 
    "futebol", "futuro", "gaiola", "galinha", "galo", "ganhar", "garfo", "garganta", "garrafa", "gato", 
    "geladeira", "gelo", "gêmeos", "generoso", "gengiva", "gente", "geografia", "gerente", "gigante", 
    "girafa", "girassol", "globo", "gordo", "gorila", "gostar", "governo", "grama", "grande", "gratuito", 
    "gravata", "gritar", "grosso", "grupo", "guardar", "guerra", "guitarra", "hambúrguer", "harpa", 
    "helicóptero", "herói", "hipopótamo", "história", "hoje", "homem", "hora", "hospital", "hotel", 
    "humor", "iate", "idade", "ideia", "idioma", "igreja", "ilha", "imaginar", "impressora", "incêndio", 
    "incrível", "índio", "infância", "inferno", "informação", "inglaterra", "ingrediente", "injeção", 
    "inseto", "inteligente", "internet", "inverno", "irmã", "irmão", "itália", "jacaré", "jamais", 
    "janeiro", "janela", "jantar", "japão", "jardim", "jarra", "javali", "joaninha", "joelho", "jogar", 
    "jornal", "jovem", "juiz", "julho", "junho", "juntar", "júpiter", "justiça", "juventude", "karatê", 
    "kiwi", "labirinto", "laboratório", "lacre", "lado", "ladrão", "lagarta", "lago", "lagoa", "lágrima", 
    "lâmpada", "lanche", "lanterna", "lápis", "laranja", "largo", "lasanha", "lata", "lavar", "leão", 
    "legume", "leite", "leitura", "lembrar", "lençol", "lenda", "língua", "linha", "limão", "limpeza", 
    "lindo", "lista", "livro", "lixo", "lobo", "loja", "longe", "louco", "lua", "lugar", "luva", "luz", 
    "maçã", "macaco", "macarrão", "machado", "madeira", "mãe", "mágico", "maio", "mala", "mamãe", "mamão", 
    "manhã", "manteiga", "mão", "mapa", "mar", "maravilha", "março", "martelo", "máscara", "matemática", 
    "medalha", "médico", "medo", "meia", "melancia", "melhor", "memória", "menina", "menino", "mensagem", 
    "mentira", "mercado", "mergulho", "mês", "mesa", "metade", "metrô", "méxico", "microfone", "milho", 
    "minuto", "mochila", "moeda", "mola", "molho", "montanha", "morango", "morder", "morrer", "mosquito", 
    "motorista", "mulher", "mundo", "música", "nadar", "nariz", "natureza", "navio", "neve", "ninho", 
    "noite", "nome", "norte", "notícia", "novembro", "nuvem", "número", "óbvio", "oceano", "óculos", 
    "ocupado", "ódio", "oeste", "oficina", "olhar", "olho", "ombro", "onda", "ontem", "onça", "opinião", 
    "oração", "orelha", "orfanato", "órgão", "orgulho", "orquestra", "osso", "outono", "outubro", "ouro", 
    "ouvido", "ovo", "oxigênio", "paciente", "pacote", "padaria", "padrinho", "pagar", "página", "pai", 
    "país", "palavra", "palhaço", "palma", "pão", "panda", "panela", "pano", "papai", "papel", 
    "parabéns", "paraíso", "parque", "parte", "partida", "pássaro", "passado", "passeio", "passo", "pasta", 
    "pastel", "pato", "patrão", "pausa", "paz", "pé", "pedra", "pegar", "peixe", "pele", "pena", "pensar", 
    "pente", "pequeno", "pera", "perder", "pergunta", "perigo", "perna", "personagem", "perto", "pescoço", 
    "pesadelo", "pescar", "pessoa", "piano", "pijama", "pimenta", "pincel", "pingente", "pinguim", "pinta", 
    "pintar", "pipoca", "piquenique", "pirata", "piscina", "pista", "pizza", "placa", "planeta", "planta", 
    "plástico", "pneu", "pobre", "poção", "poema", "poeira", "polícia", "polvo", "pombo", "ponte", "ponto", 
    "pipa", "povo", "praia", "prata", "prateleira", "prato", "prazer", "preço", "prédio", "prego", "preguiça", 
    "prender", "presente", "presidente", "preto", "primavera", "primeiro", "princesa", "príncipe", 
    "prisão", "problema", "professor", "profundo", "programa", "promessa", "pronto", "provar", "pular", 
    "pulmão", "pulseira", "quadro", "qualidade", "quando", "quarto", "quase", "queijo", "quente", "querer", 
    "quintal", "rádio", "raio", "rainha", "raiva", "ramo", "rápido", "raposa", "rato", "receita", 
    "redondo", "relógio", "remédio", "repetir", "reportagem", "restaurante", "retrato", "revista", "rei", 
    "rico", "rio", "rir", "robô", "roda", "rolha", "romance", "roupa", "roxo", "rua", "ruído", "sábado", 
    "saber", "sabiá", "sabão", "sabonete", "sabor", "saco", "sacola", "saia", "sal", "sala", "salada", 
    "sanduíche", "sangue", "sapo", "sapato", "saudade", "saúde", "seco", "segredo", "segundo", "selva", 
    "semana", "sempre", "sentar", "sentimento", "senhora", "separar", "sereia", "serpente", "serra", 
    "serviço", "setembro", "silêncio", "sino", "sirene", "skate", "sofá", "sol", "soldado", "sozinho", 
    "som", "sombra", "sonho", "sopa", "sorrir", "sorte", "sorvete", "subir", "suco", "sujo", "sul", "sumir", 
    "supermercado", "surpresa", "talher", "tamanho", "tambor", "tampa", "tarde", "tarefa", "tartaruga", 
    "tatu", "táxi", "teatro", "teclado", "tela", "telefone", "telegrama", "telescópio", "televisão", 
    "temperatura", "tempestade", "tempo", "tênis", "tentar", "terça-feira", "terra", "tesoura", "tesouro", 
    "texto", "tia", "tigela", "tigre", "tinta", "tio", "toalha", "tocar", "tomate", "torneira", "torta", 
    "tosse", "trabalho", "trator", "trem", "triste", "trovão", "tubarão", "tudo", "túnel", "turista", 
    "último", "unha", "uniforme", "universo", "urso", "urubu", "usar", "útil", "uva", "vaca", "vagão", 
    "vago", "vale", "valente", "valor", "vampiro", "vapor", "varanda", "vareta", "vaso", "vassoura", 
    "vazio", "vizinho", "vela", "velocidade", "velho", "vencedor", "vender", "veneno", "vento", "verde", 
    "verdade", "verão", "vermelho", "vespa", "vestido", "veterinário", "vez", "viagem", "vida", "vidro", 
    "vila", "vilão", "vinagre", "vinho", "violeta", "violão", "visita", "vitamina", "vitória", "viúva", 
    "viver", "vizinho", "voar", "você", "vogal", "volante", "volta", "vontade", "vovó", "vovô", "vulcão", 
    "xadrez", "xampu", "xarope", "xícara", "zero", "zoológico", "zumbi"
];